# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       meegotouch-theme
Summary:    Theme for Meego Touch based applications
Version:    0.20.36
Release:    1%{?dist}
Group:      System/Desktop
License:    LGPL v2.1
BuildArch:  noarch
URL:        http://meego.gitorious.org/meegotouch/meegotouch-theme
Source0:    %{name}-%{version}.tar.bz2
Source100:  meegotouch-theme.yaml
Requires:   libmeegotouch >= 0.20.0
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  fdupes
Provides:   duitheme > 0.19.7
Provides:   meegotouch-theme-common >= 0.20.14
Obsoletes:   duitheme <= 0.19.7
Obsoletes:   meegotouch-theme-common < 0.20.14


%description
Theme required by any MeeGo Touch library based application.
Contains the base theme files and two alternative themes with a different look.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
qmake install_prefix=/usr
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
export INSTALL_ROOT=%{buildroot}
# << install pre
%make_install 

# >> install post
%fdupes %{buildroot}%{_datadir}

# Remove known zero-length files
rm %{buildroot}/usr/share/themes/base/meegotouch/locale/ar/constants.ini
rm %{buildroot}/usr/share/themes/base/meegotouch/feedbacks/cancel/vibra.ivt
rm %{buildroot}/usr/share/themes/plankton/meegotouch/feedbacks/cancel/vibra.ivt
rm %{buildroot}/usr/share/themes/base/meegotouch/feedbacks/press-textedit-selection/audio.wav
rm %{buildroot}/usr/share/themes/base/meegotouch/feedbacks/appear-objectmenu/audio.wav
rm %{buildroot}/usr/share/themes/base/meegotouch/feedbacks/move-slider/audio.wav
# << install post






%files
%defattr(-,root,root,-)
# >> files
%defattr(-, root, root, -)
%attr(644, -, -) %{_datadir}/themes/base/meegotouch/icons
%{_datadir}/themes/base/meegotouch/svg
%{_datadir}/themes/base/meegotouch/libmeegotouchviews/style
%{_datadir}/themes/base/meegotouch/libmeegotouchextensions/style
%{_datadir}/themes/base/meegotouch/libmeegotouchcore
%{_datadir}/themes/base/meegotouch/images
%{_datadir}/themes/base/meegotouch/feedbacks
%{_datadir}/themes/base/meegotouch/camera-ui
%{_datadir}/themes/base/index.theme
%{_datadir}/themes/base/meegotouch/constants.ini
%{_datadir}/themes/base/meegotouch/ids.txt
%{_datadir}/themes/base/meegotouch/locale
%{_datadir}/themes/plankton
# << files


