[Desktop Entry]
Type=X-MeeGoTouch-Metatheme
Name=Plankton Theme
Encoding=UTF-8

; this section is here for libdui 0.19 compatibility
; remove this when libdui 0.19 is phased out
[X-DUI-Metatheme]
X-Icon = "icon-l-meegotouchtheme-plankton"
X-Inherits=base
X-Visible=true
; remove end

[X-MeeGoTouch-Metatheme]
X-Inherits=base
X-Icon = "icon-l-meegotouchtheme-plankton"
X-Visible=true
X-Libraries=meegotouchviews
