#!/bin/bash

for element in `grep -o -E "id=\"dui(.*)\"" dui*.svg | cut -d "\"" -f 2 | sort | uniq`; do 
    matches=`grep "\id=\"$element\"" *.svg | wc -l`;
    if [ $matches != "1" ]; then
	echo
	echo -ne "\e[00;31m" #red
	echo -ne "\e[1m" #bold
	echo "DUPLICATES of $element: $matches"
	echo -ne "\e[0m" #/bold
	echo -ne "\e[00m" #/red

	grep $element dui*.svg

    else
	echo -ne "\e[1;30m" #gray
	echo -n "."
	echo -ne "\e[00m" #/gray
    fi
done; 
echo
